### ISSUE TITLE
Lives count in the first level being incorrect. 

### ISSUE THREAD

**Issue by slumberingWoods** [leonellalevy/Resonance-Temple#1]
When entering the first level, the life count is supposed to be 3 but it displays 2 lives instead. 
![bugcapture2](https://user-images.githubusercontent.com/89657112/145283029-513449a3-1058-4457-b275-c5a8d2159e67.PNG)

It seems that the world starts the game with 2 lives instead of 3.

**Comment by ArielWaz** [comment]
Hey, yes so basically it is kinda worded weirdly but essentially that you are alive right now counts as the 3rd life.
