### ISSUE TITLE
Bullets, shooting and skeleton

### ISSUE THREAD

**Issue by Mubeenkh** [leonellalevy/Resonance-Temple#2]
hey guys,

Your game was fun to play. I didn't find any bugs that affect the game much. However, I was wondering if the bullets were meant to work the way it did. For example, when you shoot on the left edge, the bullet appears on the right side. 

Also, this is an idea to help the game a bit. I think placing some actors in random locations each time you restart the level would make the game a little more of a challenge.  
For the skeletons, I'm not sure if you put this already but you could make them follow the player or go after him.

**Comment by ArielWaz** [comment]
Yeah I agree, we are working on it, thanks for the feedback!
